### PR TITLE
Strip null bytes in kmods fact

### LINKED ISSUE #98: kmods fact produces null byte in parameters datastructure
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.28.0
- Ruby: 2.5.9
- Distribution: OSS
- Module version: 3.2.0

## How to reproduce (e.g Puppet code you use)

In my case Puppet ran in a libvirt VM where the parameter "virtio_mmio/device" has apparently no value. Running `puppet facts` produced:

```
[...]
      "virtio_mmio": {
        "parameters": {
          "device": "\u0000"
        },
        "used_by": [

        ]
      },
[...]
```

This produced the following error when uploading the fact to Foreman: 

```
'Action failed' error (ArgumentError): string contains null byte
```

I know Foreman could handle such input more gracefully, but `\u0000` does not look like a correct value either.

## What are you seeing

See above.

## What behaviour did you expect instead

An empty string like this:

```
[...]
      "virtio_mmio": {
        "parameters": {
          "device": ""
        },
        "used_by": [

        ]
      },
[...]
```

## Output log

See above.

### PR DESCRIPTION
**Pull request by saz**
#### Pull Request (PR) description
Puppet won't allow facts containing null bytes. This will remove any null bytes from values within the `kmods` fact

#### This Pull Request (PR) fixes the following issues
Fixes #98

### CODE REVIEW

File: lib/facter/kmod.rb [hunk 1]
```diff
@@ -24,7 +24,7 @@
             next unless File.readable?("/sys/module/#{directory}/parameters/#{param}")
 
             begin
-              kmod[directory]['parameters'][param] = File.read("/sys/module/#{directory}/parameters/#{param}").chomp
+              kmod[directory]['parameters'][param] = File.read("/sys/module/#{directory}/parameters/#{param}").chomp.delete("\u0000")
```
Comment (smortex) [inline lib/facter/kmod.rb:27]: From my tests, I only see "ASCII text" values, empty files, or files consisting of a single `\n` in parameters.  So any binary data is probably invalid?

In this case, [String#ascii_only?](https://ruby-doc.org/core-3.1.2/String.html#method-i-ascii_only-3F) should help detect this abnormal condition and raise an exception that we can catch below to ignore this parameter completely.

This is probably more consistent than striping arbitrary binary chars, and it shows the intent without the need to git-blame the code to find a commit that reference an issue on GitHub to understand why this was changed (in any case, the "why" should also go in the commit message).

Comment (kenyon) [reply lib/facter/kmod.rb:27]: Null is valid ASCII though:

```
irb(main):011:0> String.new("\u0000").ascii_only?
=> true
```

Comment (waipeng) [reply lib/facter/kmod.rb:27]: yes can confirm
```
irb(main):001:0> File.read("/sys/module/virtio_mmio/parameters/device").chomp
=> "\u0000"
irb(main):002:0> File.read("/sys/module/virtio_mmio/parameters/device").chomp.ascii_only?
=> true
```

Comment (saz) [reply lib/facter/kmod.rb:27]: @smortex  As `ascii_only?` won't help here, I'll update the commit message or do you have another idea to resolve this in a better way?

Comment (prouveyrol) [reply lib/facter/kmod.rb:27]: Hello, as it seems to me that the solution is now agreed upon, is there a defined timeline to merge this PR?
Is there something I could do to help?
This error is impacting quite a few of our servers, and this PR would be really valuable to us.

Comment (kenyon) [reply lib/facter/kmod.rb:27]: @prouveyrol if you could test this fix, I think that would help.

**Review by kenyon — APPROVED** [review]
I tested this branch on my one node that had a null byte in a kmods parameter fact, and it allowed puppet to run (finally). So I'll merge this.

For searchability, the error shown in the puppet run report log the PE console (without this patch) is `Failed to apply catalog: Could not render to json: partial character in source, but hit end`.
